{\rtf1\ansi\ansicpg950\cocoartf2868
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;\f1\fnil\fcharset0 Menlo-Bold;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww26840\viewh15600\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs22 \cf2 \CocoaLigature0 apiVersion: apps/v1\
kind: Deployment\
metadata:\
  name: nginx-vnf\
spec:\
  replicas: 1\
  selector:\
    matchLabels:\
      app: nginx-vnf\
  template:\
    metadata:\
      labels:\
        app: nginx-vnf\
    spec:\
      containers:\

\f1\b       - 
\f0\b0 name: nginx\
        image: nginx:alpine\
        ports:\

\f1\b         - 
\f0\b0 containerPort: 80\

\f1\b ---
\f0\b0 \
apiVersion: v1\
kind: Service\
metadata:\
  name: vnf-service\
spec:\
  selector:\
    app: nginx-vnf\
  ports:\

\f1\b     - 
\f0\b0 protocol: TCP\
      port: 80\
      targetPort: 80\
  type: NodePort\
}